### ISSUE TITLE
500 Error when specifying terms in a taxonomy

### ISSUE THREAD

**Issue by mikeselander** [Automattic/aggregator#51]
I've identified an error in the way that terms are run when using multiple jobs based off of terms in a single taxonomy.

I'm going to explain and make reproduction steps as best I can but do feel free to ask me questions.

**Error**
```
Catchable fatal error: Argument 1 passed to Aggregate::allowed_taxonomies() must be of the type array, object given, called in /srv/www/thesun/wp-content/plugins/aggregator-fork/class-aggregate.php on line 801 and defined in /srv/www/thesun/wp-content/plugins/aggregator-fork/class-aggregate.php on line 140
```

**Taxonomies:**
Consumer Sites - one term for Site B, one term for Site C

**Post Types:**
Default posts

**Sites:**
 - Main Site (master on all jobs, main site)
 - Site B
 - Site C

**Jobs:**
 - Main Site post -> Site B _**when**_ Consumer Sites set to Site B on post
 - Main Site post -> Site C _**when**_ Consumer Sites set to Site C on post

**To Reproduce:**
 1. Create sites, taxonomy, and jobs per the above (set up the jobs in the above order)
 2. Add a new post with Consumer Sites set to Site B - article should correctly populate to the site with no errors (using as a comparison and proof of identified issue)
 3. Add a new post with Consumer Sites set to Site C - page will 500 with the above error

**What's Happening:**
There is a cross in variables causing the variable `$orig_terms` that's defined outside the foreach loop to be constantly overridden as you loop through jobs in `push_post_data_to_blogs()`. As you loop through jobs `$orig_terms` is constantly modified by the code inside the foreach loop causing the next iteration to use the last iteration's modified and incorrect values. In this case if a job is bad on the first loop, but good on the second loop, the second loop attempts to push a `WP_Error` into `prepare_terms`.

Look at this line through ~805 to see what I'm talking about: 
https://github.com/Automattic/aggregator/blob/master/class-aggregate.php#L776

**Comment by philipjohn** [comment]
Nice find! Thanks for the detailed explanation too, that helped me to see it in the code - bit of an "aha!" moment...
