### ISSUE TITLE
Questions on functionality

### ISSUE THREAD

**Issue by trewknowledge** [Automattic/aggregator#67]
Hello, I just have a few questions around functionality:

1. I have 7 sites in my network. I would like each site to have the ability to post to any other site in the network. So a post can be synced to 1, 2, 3, or all 7 sites if the appropriate categories are checked. Is this possible?

2. When a post is synced to another site, clicking on the article takes you back to the original site the article was posted on. Is it possible that the user remains on the site the article was pushed to?

3. When a post is synced to another site it gets set as a pending. Can the post be published automatically?

**Comment by philipjohn** [comment]
Hiya,

1. This is definitely possible - the plugin is designed to work exactly in that way. When you set up the Aggregation Job you can choose which post types and taxonomies/terms are to be synced across.

2. This default behaviour can be easily overridden by removing the filter, like so: `remove_filter( 'post_link', array( 'Aggregator_Plugin', 'post_link' ) );`

3. This is not currently possible but there is discussion about adding a filter for that on #54 - pull requests welcome!

**Comment by trewknowledge** [comment]
Hi Philip,

1. Sounds good.

2. I added this filter but in my tests, it did not work. For example, I pushed a post from Site A to Site B. I then published the post in Site B. On the front-end of Site B, clicking on the post takes you back to Site A.

3. I will take a look!

Thanks for your help!

**Comment by philipjohn** [comment]
On 2, could you share the exact code you're using please?

**Comment by trewknowledge** [comment]
In functions.php I just added `remove_filter( 'post_link', array( 'Aggregator_Plugin', 'post_link' ) );`

Was there anything else I needed to add?

**Comment by philipjohn** [comment]
Sorry, it needs to be slightly different:

`remove_filter( 'post_link', array( $aggregator, 'post_link' ) );`

You may need to do `global $aggregator` but hopefully not.

**Comment by trewknowledge** [comment]
Hi @philipjohn, I adjusted the filter both with and without `global $aggregator` and got the same results. The aggregated post still links to the source site.

I am using the twentyseveteen theme for my tests. The code I am using is

```
global $aggregator;
remove_filter( 'post_link', array( $aggregator, 'post_link' ) );
```

**Comment by david-binda** [comment]
Hello @trewknowledge the Aggregator is registering it's `post_link` filter with $priority set to null ( see https://github.com/Automattic/aggregator/blob/master/class-aggregator.php#L66 and https://github.com/Automattic/aggregator/blob/master/class-plugin.php#L225 ).

Since it's not the default priority (it's 10), the `remove_filter` call needs to specify the same priority.

Following worked for me during my tests:

```
global $aggregator;
remove_filter( 'post_link', array( $aggregator, 'post_link' ), null )
```

**Comment by trewknowledge** [comment]
When I add that in and push a post to "site b" the permalink shows up correctly, but clicking into the actual post redirects be back to the original site.

Does this not happen in your test?

**Comment by philipjohn** [comment]
> the permalink shows up correctly

Where exactly are you looking at the permalink? By correctly, do you mean that the permalink points to Site B (and the aggregated copy of the post)?

I've spun up a test multisite and tried to test this more thoroughly.

I'm using twentyseventeen and adding the following code to the bottom of functions.php:

```
global $aggregator;
remove_filter( 'post_link', array( $aggregator, 'post_link' ), null );
```

I'm then loading the edit posts screen on a sub-site ("Site B"), which shows me posts that have been aggregated from the main site ("Site A").

The "View" link on the aggregated post points to the URL on Site B, as expected - the `remove_filter()` call has worked.

The redirect happens [here](https://github.com/Automattic/aggregator/blob/9466b4fe38504208471147362ff1d829cd3c679a/class-aggregator.php#L998), so you'll additionally need to do one of two things:

1. Remove the redirect completely with `remove_action( 'template_redirect', array( $aggregator, 'template_redirect' ), null );`
2. Capture the original permalink (from Site A) and stop aggregated posts redirecting back to that using the [`aggregator_should_redirect` filter](https://github.com/Automattic/aggregator/blob/9466b4fe38504208471147362ff1d829cd3c679a/class-aggregator.php#L1012).

I've just tested the first solution and that works for me for stopping the redirect. I haven't tested the second - it's a bit more involved, so if the first option works for you, go for that.

**Comment by trewknowledge** [comment]
Hi @philipjohn,

Sorry for the confusion. I was looking at the permalink on the front-end of the website to click into the post. Clicking on the permalink on the front end of "Site B" redirects me back to the post on "Site A".

Looks like I need to remove the `template_redirect` action as well to avoid this redirect.

I will give it a shot. Thanks for all your help!

**Comment by trewknowledge** [comment]
`remove_action( 'template_redirect', array( $aggregator, 'template_redirect' ), null );`

did not work for me, but setting a priority of 10 did:

`remove_action( 'template_redirect', array( $aggregator, 'template_redirect' ), 10 );`

**Comment by philipjohn** [comment]
Great! Thanks for reporting back, and glad it's working for you now.

This might have helped reveal a bug with how we set priority...
